import type { WeatherModel } from './types';

export const WEATHER_MODELS: WeatherModel[] = [
  {
    id: 'icon_seamless',
    name: 'DWD ICON',
    shortName: 'ICON',
    organization: 'Deutscher Wetterdienst',
    region: 'Global & Europe',
    color: '#0ea5e9',
    resolution: '2–11 km',
  },
  {
    id: 'icon_eu',
    name: 'DWD ICON-EU',
    shortName: 'ICON-EU',
    organization: 'Deutscher Wetterdienst',
    region: 'Europe',
    color: '#0284c7',
    resolution: '6 km',
  },
  {
    id: 'gfs_seamless',
    name: 'NOAA GFS & HRRR',
    shortName: 'GFS',
    organization: 'NOAA / NCEP',
    region: 'Global & North America',
    color: '#f97316',
    resolution: '3–25 km',
  },
  {
    id: 'meteofrance_seamless',
    name: 'Météo-France ARPEGE/AROME',
    shortName: 'Météo-France',
    organization: 'Météo-France',
    region: 'Global, Europe & France',
    color: '#a855f7',
    resolution: '1–25 km',
  },
  {
    id: 'ecmwf_ifs04',
    name: 'ECMWF IFS',
    shortName: 'IFS',
    organization: 'ECMWF',
    region: 'Global',
    color: '#6366f1',
    resolution: '9–25 km',
  },
  {
    id: 'ecmwf_aifs025',
    name: 'ECMWF AIFS (AI)',
    shortName: 'AIFS',
    organization: 'ECMWF',
    region: 'Global',
    color: '#8b5cf6',
    resolution: '25 km',
  },
  {
    id: 'ukmo_seamless',
    name: 'UK Met Office UM',
    shortName: 'UKMO',
    organization: 'UK Met Office',
    region: 'Global & UK',
    color: '#dc2626',
    resolution: '2–10 km',
  },
  {
    id: 'kma_seamless',
    name: 'KMA Korea',
    shortName: 'KMA',
    organization: 'Korea Meteorological Administration',
    region: 'Global & South Korea',
    color: '#f59e0b',
    resolution: '1.5–13 km',
  },
  {
    id: 'jma_seamless',
    name: 'JMA MSM/GSM',
    shortName: 'JMA',
    organization: 'Japan Meteorological Agency',
    region: 'Global & Japan',
    color: '#ec4899',
    resolution: '5–55 km',
  },
  {
    id: 'metno_seamless',
    name: 'MET Norway Nordic',
    shortName: 'MET Norway',
    organization: 'MET Norway',
    region: 'Nordic',
    color: '#06b6d4',
    resolution: '1 km',
  },
  {
    id: 'gem_seamless',
    name: 'Environment Canada GEM',
    shortName: 'GEM',
    organization: 'Canadian Weather Service',
    region: 'Global & Canada',
    color: '#14b8a6',
    resolution: '2.5–15 km',
  },
  {
    id: 'bom_access_global',
    name: 'BOM ACCESS-G',
    shortName: 'BOM',
    organization: 'Australian Bureau of Meteorology',
    region: 'Global',
    color: '#eab308',
    resolution: '15 km',
  },
  {
    id: 'cma_grapes_global',
    name: 'CMA GRAPES',
    shortName: 'CMA',
    organization: 'China Meteorological Administration',
    region: 'Global',
    color: '#ef4444',
    resolution: '15 km',
  },
  {
    id: 'knmi_seamless',
    name: 'KNMI HARMONIE',
    shortName: 'KNMI',
    organization: 'Royal Netherlands Meteorological Institute',
    region: 'Europe & Netherlands',
    color: '#22c55e',
    resolution: '2 km',
  },
  {
    id: 'dmi_seamless',
    name: 'DMI HARMONIE',
    shortName: 'DMI',
    organization: 'Danish Meteorological Institute',
    region: 'Denmark',
    color: '#84cc16',
    resolution: '2 km',
  },
  {
    id: 'geosphere_seamless',
    name: 'GeoSphere Austria AROME',
    shortName: 'GeoSphere',
    organization: 'GeoSphere Austria',
    region: 'Central Europe',
    color: '#f43f5e',
    resolution: '2.5 km',
  },
  {
    id: 'chmi_aladin_seamless',
    name: 'CHMI ALADIN',
    shortName: 'CHMI',
    organization: 'Czech Hydrometeorological Institute',
    region: 'Central Europe',
    color: '#d946ef',
    resolution: '1–2.3 km',
  },
  {
    id: 'meteoswiss_icon_seamless',
    name: 'MeteoSwiss ICON',
    shortName: 'MeteoSwiss',
    organization: 'MeteoSwiss',
    region: 'Central Europe',
    color: '#fbbf24',
    resolution: '1–2 km',
  },
  {
    id: 'italia_meteo_arpae_icon_2i',
    name: 'ItaliaMeteo ARPAE ICON-2I',
    shortName: 'ItaliaMeteo',
    organization: 'ItaliaMeteo / ARPAE',
    region: 'Southern Europe',
    color: '#10b981',
    resolution: '2 km',
  },
];

export const MODEL_IDS = ['ecmwf_ifs04','gfs_seamless','icon_seamless','meteofrance_seamless','jma_seamless'];

export function getModelById(id: string): WeatherModel | undefined {
  return WEATHER_MODELS.find((m) => m.id === id);
}
