/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAnalyzeWeatherImageRouteImport } from './routes/api/public/analyze-weather-image'
import { Route as ApiPublicSatelliteRouteImport } from './routes/api/public/satellite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeWeatherImageRoute =
  ApiPublicAnalyzeWeatherImageRouteImport.update({
    id: '/api/public/analyze-weather-image',
    path: '/api/public/analyze-weather-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSatelliteRoute = ApiPublicSatelliteRouteImport.update({
  id: '/api/public/satellite',
  path: '/api/public/satellite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/analyze-weather-image': typeof ApiPublicAnalyzeWeatherImageRoute
  '/api/public/satellite': typeof ApiPublicSatelliteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/analyze-weather-image': typeof ApiPublicAnalyzeWeatherImageRoute
  '/api/public/satellite': typeof ApiPublicSatelliteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/analyze-weather-image': typeof ApiPublicAnalyzeWeatherImageRoute
  '/api/public/satellite': typeof ApiPublicSatelliteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/analyze-weather-image' | '/api/public/satellite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/analyze-weather-image' | '/api/public/satellite'
  id:
    | '__root__'
    | '/'
    | '/api/public/analyze-weather-image'
    | '/api/public/satellite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAnalyzeWeatherImageRoute: typeof ApiPublicAnalyzeWeatherImageRoute
  ApiPublicSatelliteRoute: typeof ApiPublicSatelliteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze-weather-image': {
      id: '/api/public/analyze-weather-image'
      path: '/api/public/analyze-weather-image'
      fullPath: '/api/public/analyze-weather-image'
      preLoaderRoute: typeof ApiPublicAnalyzeWeatherImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/satellite': {
      id: '/api/public/satellite'
      path: '/api/public/satellite'
      fullPath: '/api/public/satellite'
      preLoaderRoute: typeof ApiPublicSatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAnalyzeWeatherImageRoute: ApiPublicAnalyzeWeatherImageRoute,
  ApiPublicSatelliteRoute: ApiPublicSatelliteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
